### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by sasikiran** [neuralet/smart-social-distancing#6]
Hi, I followed the instructions. I have JetPack 4.3 installed on TX2. This is the error I get. I tried the other repo and the result is same. 

```
INFO:__main__:Services Started.
INFO:     Started server process [14]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[TensorRT] ERROR: Could not register plugin creator:  FlattenConcat_TRT in namespace: 
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 6.2 got compute 5.3, please rebuild.
[TensorRT] ERROR: engine.cpp (1324) - Serialization Error in deserialize: 0 (Core engine deserialization failure)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "neuralet-distancing.py", line 14, in start_engine
    engine = CvEngine(config)
  File "/repo/libs/core.py", line 25, in __init__
    self.detector = Detector(self.config)
  File "/repo/libs/detectors/jetson/detector.py", line 18, in __init__
    self.net = mobilenet_ssd_v2.Detector(self.config)
  File "/repo/libs/detectors/jetson/mobilenet_ssd_v2.py", line 66, in __init__
    self.context = self._create_context()
  File "/repo/libs/detectors/jetson/mobilenet_ssd_v2.py", line 34, in _create_context
    for binding in self.engine:
TypeError: 'NoneType' object is not iterable

```

**Comment by sasikiran** [comment]
Solved this by:
1. Rebuilding `ssd_mobilenet_v2_coco` for TRT on TX2 and replacing the one that comes bundled for Nano.
2. Rebuilt `libflattenconcat.so` for TX2 and replaced the one that comes bundled for Nano.
