### ISSUE TITLE
Issue with video feeds buffering and becoming out-of-sync with each other

### ISSUE THREAD

**Issue by rlsse** [neuralet/smart-social-distancing#66]
Hi all,

I managed to get this up and running on a Jetson Nano a couple of months ago. 
Coming back to it now everything has changed! 👍

I'm running both the front-end and the processor on the Nano. I have no experience with docker so was not sure how to get the two parts communicating, eventually I got something though. I detail the steps here just in case.

I built and run everything on the Nano itself in headless mode as follows:

Modified the `config-frontend.ini` file as follows:
``` ini
[App]
Host: 0.0.0.0
Port: 8000

[Processor]
; The IP and Port on which your Processor node is runnning (according to your docker run's -p HOST_PORT:8000 ... for processor's docker run command
Host: 192.168.1.104 <-- changed this line to reflect the IP address of the Nano
Port: 8001
```

Build the docker files:
``` bash
docker build -f frontend.Dockerfile -t "neuralet/smart-social-distancing:latest-frontend" .
docker build -f jetson-web-gui.Dockerfile -t "neuralet/smart-social-distancing:latest-web-gui-jetson" .

docker build -f jetson-nano.Dockerfile -t "neuralet/smart-social-distancing:latest-jetson-nano" .
```

Start the front-end:
``` bash
sudo docker run -it -p 8000:8000 --rm neuralet/smart-social-distancing:latest-web-gui-jetson

# Output
INFO:     Started server process [1]
INFO:uvicorn.error:Started server process [1]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

Start the processor:
``` bash
sudo docker run -it --runtime nvidia --privileged -p 8001:8000 -v "$PWD/data":/repo/data -v "$PWD/config-jetson.ini":/repo/config-jetson.ini -e TZ=`./timezone.sh` neuralet/smart-social-distancing:latest-jetson-nano

# Output
video file at  /repo/data/softbio_vid.mp4 not exists, downloading...
--2020-10-15 10:46:41--  https://social-distancing-data.s3.amazonaws.com/softbio_vid.mp4
Resolving social-distancing-data.s3.amazonaws.com (social-distancing-data.s3.amazonaws.com)... 52.217.65.116
Connecting to social-distancing-data.s3.amazonaws.com (social-distancing-data.s3.amazonaws.com)|52.217.65.116|:443... connected.
HTTP request sent, awaiting response... INFO:__main__:Reporting disabled!
200 OK
Length: 25371423 (24M) [video/mp4]
Saving to: 'data/softbio_vid.mp4'

data/softbio_vid.mp4            2%[>                                                 ] 534.65K   730KB/s               INFO:libs.processor_core:Core's queue has been initiated
INFO:__main__:Core Started.
INFO:root:Starting processor core
INFO:libs.processor_core:Core is listening for commands ...
data/softbio_vid.mp4            7%[==>                                               ]   1.81M  1.17MB/s               INFO:api.processor_api:Connection established to Core's queue
data/softbio_vid.mp4            8%[===>                                              ]   2.15M  1.23MB/s               INFO:__main__:API Started.
data/softbio_vid.mp4           10%[====>                                             ]   2.47M  1.26MB/s               INFO:     Started server process [11]
INFO:uvicorn.error:Started server process [11]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
data/softbio_vid.mp4          100%[=================================================>]  24.20M  1.62MB/s    in 16s

2020-10-15 10:46:57 (1.52 MB/s) - 'data/softbio_vid.mp4' saved [25371423/25371423]

running curl 0.0.0.0:8000/process-video-cfg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0INFO:api.processor_api:process-video-cfg requests on api
INFO:api.processor_api:waiting for core's response...
INFO:libs.processor_core:command received: Commands.PROCESS_VIDEO_CFG
INFO:libs.processor_core:Setup scheduled tasks
INFO:libs.processor_core:should not send notification for camera default
INFO:libs.processor_core:started to process video ...
100     4  100     4    0     0     59      0 --:--:-- --:--:-- --:--:--    60
ok video is going to be processed
INFO:libs.engine_threading:[68] taking on 1 cameras
[TensorRT] ERROR: Could not register plugin creator:  FlattenConcat_TRT in namespace:
INFO:libs.detectors.jetson.mobilenet_ssd_v2:allocated buffers
Device is:  Jetson
Detector is:  ssd_mobilenet_v2_coco
image size:  [300, 300, 3]
INFO:libs.distancing:opened video /repo/data/softbio_vid.mp4
error: XDG_RUNTIME_DIR not set in the environment.
0:00:00.812662754    79   0x55b7599660 ERROR                default gstvaapi.c:254:plugin_init: Cannot create a VA display
INFO:libs.distancing:processed frame 1 for /repo/data/softbio_vid.mp4
INFO:libs.distancing:processed frame 101 for /repo/data/softbio_vid.mp4
INFO:libs.distancing:processed frame 201 for /repo/data/softbio_vid.mp4
INFO:libs.distancing:processed frame 301 for /repo/data/softbio_vid.mp4
```

This seems to be good so far, I start getting the graph appearing in my browser when I visit `192.168.1.104:8000`.

However, the video feeds seem to buffer and stutter a lot. Furthermore, the birds-eye view and the video feed quickly become out-of-sync with one another. If I look back at the running processor I observe something along the following lines (which happens an awful lot):

``` bash
INFO:libs.distancing:processed frame 3301 for /repo/data/softbio_vid.mp4
INFO:libs.distancing:processed frame 3401 for /repo/data/softbio_vid.mp4
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/fastapi/applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/usr/local/lib/python3.6/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/staticfiles.py", line 94, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/responses.py", line 314, in __call__
    "more_body": more_body,
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 148, in send
    await send(message)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/http/h11_impl.py", line 483, in send
    output = self.conn.send(event)
  File "/usr/local/lib/python3.6/dist-packages/h11/_connection.py", line 469, in send
    data_list = self.send_with_data_passthrough(event)
  File "/usr/local/lib/python3.6/dist-packages/h11/_connection.py", line 502, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/usr/local/lib/python3.6/dist-packages/h11/_writers.py", line 78, in __call__
    self.send_data(event.data, write)
  File "/usr/local/lib/python3.6/dist-packages/h11/_writers.py", line 98, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/fastapi/applications.py", line 181, in __call__
    await super().__call__(scope, receive, send)  # pragma: no cover
  File "/usr/local/lib/python3.6/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/staticfiles.py", line 94, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.6/dist-packages/starlette/responses.py", line 314, in __call__
    "more_body": more_body,
  File "/usr/local/lib/python3.6/dist-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/cors.py", line 148, in send
    await send(message)
  File "/usr/local/lib/python3.6/dist-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/http/h11_impl.py", line 483, in send
    output = self.conn.send(event)
  File "/usr/local/lib/python3.6/dist-packages/h11/_connection.py", line 469, in send
    data_list = self.send_with_data_passthrough(event)
  File "/usr/local/lib/python3.6/dist-packages/h11/_connection.py", line 502, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/usr/local/lib/python3.6/dist-packages/h11/_writers.py", line 78, in __call__
    self.send_data(event.data, write)
  File "/usr/local/lib/python3.6/dist-packages/h11/_writers.py", line 98, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

My questions are; Is this expected behavior? Is the software not robust/mature enough at this stage? Is there something wrong with how I have configured the docker images or how I am running them? Is it the Nano which is just not powerful enough (e.g. in terms of pfs, or for running both processor and serving front-end)?

I only ask because I seem to recall that the simpler version I used some months back worked better for me. The front-end was super trivial, but it didn't suffer from these issues. I'm happy to roll back to that older version if required but first wanted to check this is not something that can be addressed.

Many thanks

**Comment by rlsse** [comment]
Likely related to #25

**Comment by renzodgc** [comment]
Hey, we just got around checking these old issues, sorry about the delay.

The video_logger and streaming of it in the frontend client still have room for improvement as they stutter a fair bit, although all in all its performance should be decent, the Jetson being sufficient enough to process 15FPS from a real live stream. Stutter issues will be more predominant when working with a video file because instead of losing frames to cope with the processing speed the processor will take longer to process all the video's frames).

Doing significant improvements in the video_logger and the client's streaming is not part of the scope of the current developing plan (we are focusing more on analytics and multiple camera support).

Considering the multiple changes that followed since the opening of this issue I can only suggest re-testing it (ideally with an RTSP stream or a video that contains less FPS) and seeing if it works well for your necessities.

I don't think anything particularly was downgraded performance-wise in regards to the live feed comparing to a previous version, so I don't think rolling back will help much in solving the issue. As the Web Client stills downloads the video inside your local LAN displaying it on the browser (it never travels outside the LAN).

Feel free to try testing again and report back. Elsewise I'll close this issue in a week :)

**Comment by saket424** [comment]
@renzodgc 
Thanks for the thoughtful note. You can close this issue and I will report if i have any issues with an rtsp source as these stuttering problems appear to be related to video files and not live streams

**Comment by rlsse** [comment]
@renzodgc 
As echoed by **saket**, your detailed and insightful response is much appreciated 👍 I too will try again and report back if any issues occur with an RTSP stream.

Many thanks!
